{
  "Uuid": "fa3dab03-0e35-4504-9911-558f43071d14",
  "IsCustomNode": true,
  "Category": "Link_COM_Acad.DynAXDBLib.AcadDocument",
  "Description": "Getting an AcadDocument instance from current Civil 3D Dynamo document (node Document.Current)",
  "Name": "ConnectToAcadDoc",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "Autodesk.AutoCAD.DynamoNodes.Document.Current",
      "Id": "70c9eb083072427fb1fb5ff893192a68",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b0724408f6004ab582bad422c17a1fda",
          "Name": "Document",
          "Description": "Document",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get the current AutoCAD document.\n\nDocument.Current: Document"
    },
    {
      "ConcreteType": "PythonNodeModels.PythonNode, PythonNodeModels",
      "NodeType": "PythonScriptNode",
      "Code": "# Load the Python Standard and DesignScript Libraries\r\nimport sys\r\nimport clr\r\n\r\n# Add Assemblies for AutoCAD\r\nclr.AddReference('AcMgd')\r\nclr.AddReference('AcDbMgd')\r\n\r\n# Import references from AutoCAD\r\nfrom Autodesk.AutoCAD.Runtime import *\r\nfrom Autodesk.AutoCAD.ApplicationServices import *\r\nfrom Autodesk.AutoCAD.DatabaseServices import *\r\n\r\n# The inputs to this node will be stored as a list in the IN variables.\r\ndataEnteringNode = IN\r\n\r\nadoc = Application.DocumentManager.MdiActiveDocument\r\nacad_doc = DocumentExtension.GetAcadDocument(adoc)\r\n\r\nOUT = acad_doc\r\n",
      "Engine": "IronPython2",
      "VariableInputPorts": true,
      "Id": "629bc127a38e4c66a201df620e70607a",
      "Inputs": [
        {
          "Id": "a9b5a3cf5a514c63996833e1734db086",
          "Name": "IN[0]",
          "Description": "Input #0",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "e09d2fcb0ccc402b8c0fa11203687da2",
          "Name": "OUT",
          "Description": "Result of the python script",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Disabled",
      "Description": "Runs an embedded Python script."
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadDocument.AcadDocument@var",
      "Id": "638f11764e484e569c50cb66a2f6b2f9",
      "Inputs": [
        {
          "Id": "d8df76dba01b4365ba8b3d19ed875352",
          "Name": "AcadDocument_object",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "390089bad5714355aa2a1629208884f5",
          "Name": "AcadDocument",
          "Description": "AcadDocument",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Cast intrafce Autodesk.AutoCAD.Interop.AcadDocument to that class. Use only with Python-node ByCurrentDocument!\n\nAcadDocument.AcadDocument (AcadDocument_object: var): AcadDocument"
    }
  ],
  "Connectors": [
    {
      "Start": "b0724408f6004ab582bad422c17a1fda",
      "End": "a9b5a3cf5a514c63996833e1734db086",
      "Id": "a44b3984b86f4fe4a24cca2d1eb037f2",
      "IsHidden": "False"
    },
    {
      "Start": "e09d2fcb0ccc402b8c0fa11203687da2",
      "End": "d8df76dba01b4365ba8b3d19ed875352",
      "Id": "116009dffca5482d9886c3aabf5236ab",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "Link_COM_Acad",
      "Version": "0.1.7",
      "ReferenceType": "Package",
      "Nodes": [
        "638f11764e484e569c50cb66a2f6b2f9"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.13.1.3887",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "Document.Current",
        "ShowGeometry": true,
        "Id": "70c9eb083072427fb1fb5ff893192a68",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 309.0,
        "Y": 259.0
      },
      {
        "Name": "DocumentExtension.GetAcadDocument()",
        "ShowGeometry": true,
        "Id": "629bc127a38e4c66a201df620e70607a",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 595.39007170444961,
        "Y": 261.49812042848396
      },
      {
        "Name": "AcadDocument.AcadDocument",
        "ShowGeometry": true,
        "Id": "638f11764e484e569c50cb66a2f6b2f9",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1046.2396168840296,
        "Y": 262.67143949401895
      }
    ],
    "Annotations": [],
    "X": -215.0,
    "Y": 3.0,
    "Zoom": 1.0
  }
}