{
  "Uuid": "39755664-b4d9-4557-8c46-3b50c62535e9",
  "IsCustomNode": true,
  "Category": "Link_COM_Acad.DynAXDBLib.AcadApplication",
  "Description": "Connect (or start) to AutoCAD 2020",
  "Name": "ConnectAcadApp_2020",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadApplication.AcadApplicationVersions",
      "Id": "beb6d0e68acd46e5a62944bcead178af",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "b00f527fedb44c22a662c5ff96eb7efd",
          "Name": "AutoCAD 2010",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "43fde6f7accf4abcb190f51430aacc94",
          "Name": "AutoCAD 2011",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "a2640d13d0064004ac99fcf7565c70ec",
          "Name": "AutoCAD 2012",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "235c84bde5374cb79fdcf2d4d56d07d3",
          "Name": "AutoCAD 2013",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "49f588bd6bb14c019d129ccfb7c3ba2f",
          "Name": "AutoCAD 2014",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "59cdfbfcfb7b4252ab5a42c48be0fefd",
          "Name": "AutoCAD 2015",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fb08cfef6c1f42b593e87df750339a2d",
          "Name": "AutoCAD 2016",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "31409d51620d4e849978aa5fbc112dcf",
          "Name": "AutoCAD 2017",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "31c16212e4eb4277bd441f76f14419e1",
          "Name": "AutoCAD 2018",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "b31c7ee36f334aa691afa068fe0857ac",
          "Name": "AutoCAD 2019",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "705600ebeb524da98815236340d2ab78",
          "Name": "AutoCAD 2020",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "285752c827ff42758e9365815724714f",
          "Name": "AutoCAD 2021",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "cb5e388edefb446f8fccd58af12bff96",
          "Name": "AutoCAD 2022",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "2026e5691f9a4b8daf6ce6ed31e2c97d",
          "Name": "AutoCAD 2023",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "ff17d109671f4236abe79112d448a0f7",
          "Name": "AutoCAD 2024",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get ProgID identificators for AutoCAD 2010-2024. Old versions may be no supported\n\nAcadApplication.AcadApplicationVersions ( ): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadApplication.AcadApplication@string",
      "Id": "e2488587d7c04f389bb18abed1471b49",
      "Inputs": [
        {
          "Id": "525ccf1a2c274f30a8e7f2f9d337c845",
          "Name": "progID",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "961c4bcb9ea14865b238f44d6430de1f",
          "Name": "AcadApplication",
          "Description": "AcadApplication",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Use AcadApplicationVersions to get progID data\n\nAcadApplication.AcadApplication (progID: string): AcadApplication"
    }
  ],
  "Connectors": [
    {
      "Start": "ff17d109671f4236abe79112d448a0f7",
      "End": "525ccf1a2c274f30a8e7f2f9d337c845",
      "Id": "28e13bb7fbd34527bc40a325fe134add",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "Link_COM_Acad",
      "Version": "0.0.2",
      "ReferenceType": "Package",
      "Nodes": [
        "beb6d0e68acd46e5a62944bcead178af",
        "e2488587d7c04f389bb18abed1471b49"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.13.1.3887",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "AcadApplication.AcadApplicationVersions",
        "ShowGeometry": true,
        "Id": "beb6d0e68acd46e5a62944bcead178af",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 718.5,
        "Y": 433.0
      },
      {
        "Name": "AcadApplication.AcadApplication",
        "ShowGeometry": true,
        "Id": "e2488587d7c04f389bb18abed1471b49",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 1261.5,
        "Y": 909.0
      }
    ],
    "Annotations": [],
    "X": 0.0,
    "Y": 0.0,
    "Zoom": 1.0
  }
}