{
  "Uuid": "71a7dabd-1111-41ec-971a-664bf2f7c935",
  "IsCustomNode": true,
  "Category": "Link_COM_Acad.DynAXDBLib.AcadApplication",
  "Description": "Connect (or start) to AutoCAD 2024",
  "Name": "ConnectAcadApp_2024",
  "ElementResolver": {
    "ResolutionMap": {}
  },
  "Inputs": [],
  "Outputs": [],
  "Nodes": [
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadApplication.AcadApplicationVersions",
      "Id": "a928399c8e434f2291aa7f8533c18948",
      "Inputs": [],
      "Outputs": [
        {
          "Id": "865c1ae88a3648338d72ca6607778f46",
          "Name": "AutoCAD 2010",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "0a09f9d3605b4327aca85b8db0710cf4",
          "Name": "AutoCAD 2011",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f6ba7070d910479492f50892341fc50d",
          "Name": "AutoCAD 2012",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "218cec24977b4e218d26a26ed0165889",
          "Name": "AutoCAD 2013",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "d0090c7292ca49be86c064b40a7efe78",
          "Name": "AutoCAD 2014",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "03421ade13134461841d14719d5cc8a6",
          "Name": "AutoCAD 2015",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "deaa528f75bf46a0a21fcbb1b84b7b21",
          "Name": "AutoCAD 2016",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "aa307fde51e948a39baf69e5d925edab",
          "Name": "AutoCAD 2017",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "f518b8390bd14cf4880f542fdf1a2d5f",
          "Name": "AutoCAD 2018",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "06247c3e2cf447df811257c8d935aa93",
          "Name": "AutoCAD 2019",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "82a686ca59e84f00ad3fa5e790cd238b",
          "Name": "AutoCAD 2020",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "454ff52f537146eb84dc71b0141bb078",
          "Name": "AutoCAD 2021",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "40a1b7ddfc5f4bba89dac8b1439b5387",
          "Name": "AutoCAD 2022",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "6252f6c1db244ad79ac67e1eafdac152",
          "Name": "AutoCAD 2023",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        },
        {
          "Id": "fd3a50a8391d4610abdccaaa5625587c",
          "Name": "AutoCAD 2024",
          "Description": "var",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get ProgID identificators for AutoCAD 2010-2024. Old versions may be no supported\n\nAcadApplication.AcadApplicationVersions ( ): var[]..[]"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadApplication.AcadApplication@string",
      "Id": "6b14bd56a3e44f0693827e90db561c4d",
      "Inputs": [
        {
          "Id": "f6ef3b30357b441083c3e0400ea7f5f1",
          "Name": "progID",
          "Description": "string",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "b338cb52d6ec4d25bfc5557b76a4496f",
          "Name": "AcadApplication",
          "Description": "AcadApplication",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Use AcadApplicationVersions to get progID data\n\nAcadApplication.AcadApplication (progID: string): AcadApplication"
    },
    {
      "ConcreteType": "Dynamo.Graph.Nodes.ZeroTouch.DSFunction, DynamoCore",
      "NodeType": "FunctionNode",
      "FunctionSignature": "DynAXDBLib.AcadApplication.ActiveDocument",
      "Id": "ab1282e9817c4e7fa499ca2750052767",
      "Inputs": [
        {
          "Id": "015680e522294993bf011464ff76f20d",
          "Name": "acadApplication",
          "Description": "DynAXDBLib.AcadApplication",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Outputs": [
        {
          "Id": "da6902f825be402685e7c5ec1a719b5a",
          "Name": "AcadDocument",
          "Description": "AcadDocument",
          "UsingDefaultValue": false,
          "Level": 2,
          "UseLevels": false,
          "KeepListStructure": false
        }
      ],
      "Replication": "Auto",
      "Description": "Get active drawing if it exists\n\nAcadApplication.ActiveDocument: AcadDocument"
    }
  ],
  "Connectors": [
    {
      "Start": "fd3a50a8391d4610abdccaaa5625587c",
      "End": "f6ef3b30357b441083c3e0400ea7f5f1",
      "Id": "7967cb2747f54a74b420c5089abec7d5",
      "IsHidden": "False"
    },
    {
      "Start": "b338cb52d6ec4d25bfc5557b76a4496f",
      "End": "015680e522294993bf011464ff76f20d",
      "Id": "819ee094ad3240deac941920eeedb6ce",
      "IsHidden": "False"
    }
  ],
  "Dependencies": [],
  "NodeLibraryDependencies": [
    {
      "Name": "Link_COM_Acad",
      "Version": "0.0.2",
      "ReferenceType": "Package",
      "Nodes": [
        "a928399c8e434f2291aa7f8533c18948",
        "6b14bd56a3e44f0693827e90db561c4d",
        "ab1282e9817c4e7fa499ca2750052767"
      ]
    }
  ],
  "Author": "None provided",
  "Bindings": [],
  "View": {
    "Dynamo": {
      "ScaleFactor": 1.0,
      "HasRunWithoutCrash": false,
      "IsVisibleInDynamoLibrary": true,
      "Version": "2.13.1.3887",
      "RunType": "Manual",
      "RunPeriod": "1000"
    },
    "Camera": {
      "Name": "Background Preview",
      "EyeX": -17.0,
      "EyeY": 24.0,
      "EyeZ": 50.0,
      "LookX": 12.0,
      "LookY": -13.0,
      "LookZ": -58.0,
      "UpX": 0.0,
      "UpY": 1.0,
      "UpZ": 0.0
    },
    "ConnectorPins": [],
    "NodeViews": [
      {
        "Name": "AcadApplication.AcadApplicationVersions",
        "ShowGeometry": true,
        "Id": "a928399c8e434f2291aa7f8533c18948",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 69.5,
        "Y": 40.0
      },
      {
        "Name": "AcadApplication.AcadApplication",
        "ShowGeometry": true,
        "Id": "6b14bd56a3e44f0693827e90db561c4d",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 612.5,
        "Y": 516.0
      },
      {
        "Name": "AcadApplication.ActiveDocument",
        "ShowGeometry": true,
        "Id": "ab1282e9817c4e7fa499ca2750052767",
        "IsSetAsInput": false,
        "IsSetAsOutput": false,
        "Excluded": false,
        "X": 984.05399568034579,
        "Y": 515.39956803455721
      }
    ],
    "Annotations": [],
    "X": -388.4175,
    "Y": -155.44999999999993,
    "Zoom": 1.1575
  }
}